/// Auto-generated by build/package-app.sh — DO NOT EDIT BY HAND, overwritten on every real
/// packaging run (and restored to the checked-in placeholder afterward). SHA-256 tree hash of
/// Contents/Resources/cli-src/ exactly as staged for this build.
public enum GeneratedCLIManifest {
    public static let expectedTreeHashHex = "fdb766cc3e8e3d218a5ae3c85fc5ad51da3a44ad3fb52bad182004a6d32c2684"
}
